Django_Level_Four/learning_template/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
        url(r'^relative/$',views.relative,name='relative'),
        url(r'^other/$',views.other,name='other')
]

Django_Level_Four/learning_template/learning_template/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import include

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls'))
]

Django_Level_Four/learning_template/basic_app/models.py
from django.db import models

# Create your models here.

Django_Level_Four/learning_template/basic_app/views.py
from django.shortcuts import render

# Create your views here.
#def index(request):
#    return render(request,'basic_app/index.html')

# This example is for template filter
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request, 'basic_app/index.html',context_dict)

# for other page
def other(request):
    return render(request, 'basic_app/other.html')

#for relative uRL page
def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

Django_Level_Four/learning_template/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

</head>
<body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="#">BRAND</a></li>
                    <li><a class="navbar-link" href="#">Admin</a></li>
                    <li><a class="navbar-link" href="#">Other</a></li>
                </ul>
            </div>
        </nav>
        <div class="container">
             {% block body_block %}
            <!--Anything outside of this block will be inherited if you extend! --->
             {% endblock %}
        </div>
</body>
</html>

Django_Level_Four/learning_template/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html "%}
    {% block body_block %}
    <h1>WELCOME TO INDEX</h1>
    <h2> This is index.html page showing </h2>
    {{ text|cut:'hello' }}
    {{ number }}
{% endblock %}

Django_Level_Four/learning_template/templates/basic_app/other.html
<!DOCTYPE html>
{% extends  "basic_app/base.html "%}
{% block body_block %}
    <h1>WELCOME TO OTEHRS</h1>
    <h2> This is an example of template inheritance! </h2>
{% endblock %}

Django_Level_Four/learning_template/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>RELAATIVE URL</title>
</head>
<body>
        <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
        <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
        <a href="{% url 'admin:index' %}">ADMIN</a>
        <a href="{% url 'index' %}">LINKED TO INDEX</a>
</body>
</html>